from sentence_transformers import SentenceTransformer


class EmbeddingService:
    """
    Generates dense vector embeddings for document chunks
    using the configured embedding model.
    """

    def __init__(self, model_name: str):
        self.model = SentenceTransformer(model_name)

    def generate_embeddings(
        self,
        texts: list[str],
    ) -> list[list[float]]:
        """
        Generate embeddings for a batch of texts.
        Returns one embedding vector for each input text.
        """

        if not texts:
            return []

        embeddings = self.model.encode(
            texts,
            convert_to_numpy=True,
        )

        if len(embeddings) != len(texts):
            raise ValueError(
                "Embedding count does not match input count."
            )

        result = embeddings.tolist()

        for embedding in result:
            if not embedding:
                raise ValueError(
                    "Embedding model returned an empty vector."
                )

        return result

    def get_embedding_dimension(self) -> int:
        """
        Return the dimensionality of the embedding vectors
        generated by the configured model.
        """

        return self.model.get_sentence_embedding_dimension()