"""added 1 more column in document chunk model

Revision ID: 1a3f9cf499f3
Revises: 4bcbe16a7369
Create Date: 2026-08-07 22:49:52.435415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3f9cf499f3'
down_revision: Union[str, Sequence[str], None] = '4bcbe16a7369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_status', sa.String(length=50), nullable=False, server_default="PENDING"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_status')
    # ### end Alembic commands ###
