"""add pdf extraction fields

Revision ID: 99ac09dc2ada
Revises: 4cf779b7ab57
Create Date: 2026-08-05 13:58:50.182665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ac09dc2ada'
down_revision: Union[str, Sequence[str], None] = '4cf779b7ab57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extraction_status', sa.String(length=50), nullable=False, server_default="PENDING"))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'extraction_status')
    # ### end Alembic commands ###
